### ISSUE TITLE
[GER] Rhein-Radar without color

### ISSUE THREAD

**Issue by EisernUnion** [lennycolton/vatglasses-data#53] opened 2023-03-25 18:24 UTC
@jannikvogel 
Rhein-Radar is online but without any color (or not visible on dark map)

![Missing_Color_Rhein-Radar](https://user-images.githubusercontent.com/42810795/227734888-7ceef96e-54ca-4b87-a872-507a40f86e43.png)

**Comment by MatisseBE** [comment] 2023-03-25 18:46
Duplicate of https://github.com/lennycolton/vatglasses-data/issues/24 (Langen radar)

**Closed as not planned** 2023-03-25 22:47 UTC
Labels: duplicate
